version: '2'
services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./website:/website
    links:
      - php
  php:
    build: .
    ports:
      - 9000:9000
    volumes:
      - ./website:/website
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user@postgres/mydb
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8081:80"
    links:
      - postgres
    volumes:
      - ./db_admin:/var/lib/pgadmin
